# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityFlaw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('Exploitability', models.TextField(blank=True, null=True)),
                ('Prevalence', models.TextField(blank=True, null=True)),
                ('Detectability', models.TextField(blank=True, null=True)),
                ('Impact', models.TextField(blank=True, null=True)),
                ('OWASP', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
