# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securityflaw',
            old_name='Detectability',
            new_name='detectability',
        ),
        migrations.RenameField(
            model_name='securityflaw',
            old_name='Exploitability',
            new_name='exploitability',
        ),
        migrations.RenameField(
            model_name='securityflaw',
            old_name='Impact',
            new_name='impact',
        ),
        migrations.RenameField(
            model_name='securityflaw',
            old_name='Prevalence',
            new_name='prevalence',
        ),
    ]
